EXTENSION_ID = "user.dual_arm.task"
WINDOW_TITLE = "Dual Arm Task"

RIGHT_GRIPPER_IDX = 6
LEFT_GRIPPER_IDX = 7

# arm1 gripper (goods)
GRIP1_OPEN_R = -0.005
GRIP1_OPEN_L = 0.005
GRIP1_CLOSE_R = -0.001
GRIP1_CLOSE_L = 0.001

# arm2 gripper (lid)
GRIP2_OPEN_R = -0.02
GRIP2_OPEN_L = 0.02
GRIP2_CLOSE_R = -0.015
GRIP2_CLOSE_L = 0.015

MOVE_STEPS = 100
GRIP_STEPS = 40
HOLD_FRAMES = 10
RELEASE_SETTLE_FRAMES = 8
RELEASE_AFTER_FRAMES = 5
SAFE_WAIT_HOLD_FRAMES = 10

STATUS_IDLE = "Idle"
STATUS_PREPARING = "Preparing"
STATUS_OPENING_LID = "Opening Lid"
STATUS_PLACING_OBJECT = "Placing Object"
STATUS_CLOSING_LID = "Closing Lid"
STATUS_COMPLETED = "Completed"
STATUS_ERROR = "Error"
